services:
  proxy_wo_user:
    build:
      context: .
      target: proxy_wo_user
      args:
        build_time_proxy: "${build_time_proxy:-}"
    restart: "${restart:-no}"
    environment:
      proxy_user: ${proxy_user}
      proxy_pwd: ${proxy_pwd}
      proxy_host_port: ${proxy_host_port}
    ports:
      - "3128:3128"
